//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicDent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consultas_Tratamientos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Consultas_Tratamientos()
        {
            this.Historial_Clinico = new HashSet<Historial_Clinico>();
        }
    
        public int id_consulta_tratamiento { get; set; }
        public int id_consulta { get; set; }
        public int id_tratamiento { get; set; }
        public int cantidad { get; set; }
        public decimal total { get; set; }
    
        public virtual Consulta Consulta { get; set; }
        public virtual Tratamientos Tratamientos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Historial_Clinico> Historial_Clinico { get; set; }
    }
}
