//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicDent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consulta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Consulta()
        {
            this.Consultas_Tratamientos = new HashSet<Consultas_Tratamientos>();
            this.Pagos = new HashSet<Pagos>();
        }
    
        public int id_consulta { get; set; }
        public int id_cita { get; set; }
        public int id_dentista { get; set; }
        public int id_paciente { get; set; }
        public System.DateTime fecha_consulta { get; set; }
        public string diagnostico { get; set; }
        public string observaciones { get; set; }
        public string recomendaciones { get; set; }
        public bool requiere_tratamiento { get; set; }
    
        public virtual Citas Citas { get; set; }
        public virtual Dentistas Dentistas { get; set; }
        public virtual Pacientes Pacientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consultas_Tratamientos> Consultas_Tratamientos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pagos> Pagos { get; set; }
    }
}
