//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicDent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historial_Pagos
    {
        public int id_historial_pago { get; set; }
        public Nullable<int> id_cuota { get; set; }
        public int id_pago { get; set; }
        public string estado { get; set; }
    
        public virtual Pagos_Cuotas Pagos_Cuotas { get; set; }
        public virtual Pagos Pagos { get; set; }
    }
}
