//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicDent.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClinicaDentalAzure : DbContext
    {
        public ClinicaDentalAzure()
            : base("name=ClinicaDentalAzure")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Citas> Citas { get; set; }
        public virtual DbSet<Consulta> Consulta { get; set; }
        public virtual DbSet<Consultas_Tratamientos> Consultas_Tratamientos { get; set; }
        public virtual DbSet<Dentistas> Dentistas { get; set; }
        public virtual DbSet<Historial_Clinico> Historial_Clinico { get; set; }
        public virtual DbSet<Historial_Pagos> Historial_Pagos { get; set; }
        public virtual DbSet<Inventario> Inventario { get; set; }
        public virtual DbSet<Materiales> Materiales { get; set; }
        public virtual DbSet<Pacientes> Pacientes { get; set; }
        public virtual DbSet<Pagos> Pagos { get; set; }
        public virtual DbSet<Pagos_Cuotas> Pagos_Cuotas { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Tipo_Cobro> Tipo_Cobro { get; set; }
        public virtual DbSet<Tratamientos> Tratamientos { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
