//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicDent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tratamientos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tratamientos()
        {
            this.Consultas_Tratamientos = new HashSet<Consultas_Tratamientos>();
        }
    
        public int id_tratamiento { get; set; }
        public int id_tipo_cobro { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public decimal costo { get; set; }
        public int duracion_estimada { get; set; }
        public bool seguimiento { get; set; }
        public string dientes_seleccionados { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consultas_Tratamientos> Consultas_Tratamientos { get; set; }
        public virtual Tipo_Cobro Tipo_Cobro { get; set; }
    }
}
